USE [master]
GO

/****** Object:  Database [RTDB]    Script Date: 3/19/2015 2:08:24 PM ******/
DROP DATABASE [RTDB]
GO

/****** Object:  Database [RTDB]    Script Date: 3/19/2015 2:08:24 PM ******/
CREATE DATABASE [RTDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RTDB', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\RTDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RTDB_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\RTDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RTDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RTDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RTDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RTDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RTDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RTDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RTDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [RTDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RTDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [RTDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RTDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RTDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RTDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RTDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RTDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RTDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RTDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RTDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RTDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RTDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RTDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RTDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RTDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RTDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RTDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RTDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RTDB] SET  MULTI_USER 
GO

ALTER DATABASE [RTDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RTDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RTDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RTDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [RTDB] SET  READ_WRITE 
GO


