// Automatically generated by StringsExtractor
#ifndef _STRING_TABLE_H_
#define _STRING_TABLE_H_

char *ORIGINAL_STRINGS_TABLE[] ={
    "Hello world",
    "This is a string",
    "This is a string with esc\x61pe characters",
    "\"Objet geometries\" LTD"
};

const int START_RESOURCE_ID = 0;
const int STRING_TABLE_SIZE = 4;

#endif

