// Automatically generated by StringsExtractor
#ifndef _STRING_TABLE_H_
#define _STRING_TABLE_H_

char *ORIGINAL_STRINGS_TABLE[] ={
    "objet geometries",
    "ran \"peleg",
    "the boss"
};

const int START_RESOURCE_ID = 0;
const int STRING_TABLE_SIZE = 3;

#endif

