// Decompiled by DJ v3.10.10.93 Copyright 2007 Atanas Neshkov  Date: 11/9/2015 4:17:27 PM
// Home Page: http://members.fortunecity.com/neshkov/dj.html  http://www.neshkov.com/dj.html - Check often for new version!
// Decompiler options: packimports(3) 
// Source File Name:   ExceptClass.java

package vm.apps;

import token.classes.Except;
import token.classes.Sys;

public class ExceptClass
{

    public ExceptClass()
    {
    }

    public void getException(int i)
    {
        switch(i)
        {
        case 1: // '\001'
            throw Except.genException(99, "this is exception generated by myslef");

        case 2: // '\002'
            throw Except.ArithmeticException("Not today honey");

        case 3: // '\003'
            throw Except.ClassFormatError("I had better days");

        case 4: // '\004'
            throw Except.ArithmeticException("I hate mondays");

        case 5: // '\005'
            throw Except.OutOfMemoryError("TGIF");

        case 6: // '\006'
            throw Except.InternalError("What a lousy day");

        case 8: // '\b'
            throw Except.SecurityException("Hope for better days");

        case 9: // '\t'
            throw Except.ArrayIndexOutOfBoundsException("Its my lucky day");

        case 10: // '\n'
            throw Except.genException(10, "C1");

        case 7: // '\007'
        default:
            throw Except.genException(99, "default exception");
        }
    }

    public int getMessage(byte returnMsg[])
        throws Except
    {
        RuntimeException e = Except.genException(99, "this is exception generated by myslef");
        String MessageStr = e.getMessage();
        byte tmp[] = MessageStr.getBytes();
        Sys.memCpy(returnMsg, 0, tmp, 0, tmp.length);
        return 0;
    }
}