//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSS.MVVM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSS.MVVM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding burning action to history....
        /// </summary>
        internal static string AddBurningActionToHistory {
            get {
                return ResourceManager.GetString("AddBurningActionToHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS-BSS.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be greater than {1}..
        /// </summary>
        internal static string ArgumentMustNotBeGreaterMessage {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeGreaterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be smaller than {1}..
        /// </summary>
        internal static string ArgumentMustNotBeSmallerMessage {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeSmallerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch end time:.
        /// </summary>
        internal static string BatchEndTime {
            get {
                return ResourceManager.GetString("BatchEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Number:.
        /// </summary>
        internal static string BatchNumber {
            get {
                return ResourceManager.GetString("BatchNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch numbers were read successfully..
        /// </summary>
        internal static string BatchNumbersReadSuccessfully {
            get {
                return ResourceManager.GetString("BatchNumbersReadSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch start time:.
        /// </summary>
        internal static string BatchStartTime {
            get {
                return ResourceManager.GetString("BatchStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burning....
        /// </summary>
        internal static string Burning {
            get {
                return ResourceManager.GetString("Burning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of cycles.
        /// </summary>
        internal static string BurningAttemptCount {
            get {
                return ResourceManager.GetString("BurningAttemptCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of burnings:.
        /// </summary>
        internal static string BurningAttemptsCount {
            get {
                return ResourceManager.GetString("BurningAttemptsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burning Date.
        /// </summary>
        internal static string BurningDate {
            get {
                return ResourceManager.GetString("BurningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burning material info on tag #{0} ended..
        /// </summary>
        internal static string BurningEnded {
            get {
                return ResourceManager.GetString("BurningEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material info was burned successfully on tag #{0}..
        /// </summary>
        internal static string BurningEndedSuccessfully {
            get {
                return ResourceManager.GetString("BurningEndedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed burning material info on tag #{0}..
        /// </summary>
        internal static string BurningFailed {
            get {
                return ResourceManager.GetString("BurningFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burning material info on tag #{0} started....
        /// </summary>
        internal static string BurningInProcess {
            get {
                return ResourceManager.GetString("BurningInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burning.
        /// </summary>
        internal static string BurningState {
            get {
                return ResourceManager.GetString("BurningState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Name.
        /// </summary>
        internal static string BurningStation {
            get {
                return ResourceManager.GetString("BurningStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burning Time.
        /// </summary>
        internal static string BurningTime {
            get {
                return ResourceManager.GetString("BurningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burning/Verification Privileges:.
        /// </summary>
        internal static string BurningVerificationPrivileges {
            get {
                return ResourceManager.GetString("BurningVerificationPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of burnings in batch:.
        /// </summary>
        internal static string BurnsCountLot {
            get {
                return ResourceManager.GetString("BurnsCountLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull burnings on batch:.
        /// </summary>
        internal static string BurnsCountLotSuccess {
            get {
                return ResourceManager.GetString("BurnsCountLotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of burnings on session:.
        /// </summary>
        internal static string BurnsCountSession {
            get {
                return ResourceManager.GetString("BurnsCountSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull burnings on session:.
        /// </summary>
        internal static string BurnsCountSessionSuccess {
            get {
                return ResourceManager.GetString("BurnsCountSessionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burning signed tag information....
        /// </summary>
        internal static string BurnSignedTagInfo {
            get {
                return ResourceManager.GetString("BurnSignedTagInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot communicate with central burning server.
        /// </summary>
        internal static string CannotCommunicateWithCBS {
            get {
                return ResourceManager.GetString("CannotCommunicateWithCBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag is blank:
        ///Please burn tag in burning mode..
        /// </summary>
        internal static string CannotCorrectBlankTag {
            get {
                return ResourceManager.GetString("CannotCorrectBlankTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot exit state {0}..
        /// </summary>
        internal static string CannotExitMessage {
            get {
                return ResourceManager.GetString("CannotExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot transit from state {0} to state {1}..
        /// </summary>
        internal static string CannotTransitMessage {
            get {
                return ResourceManager.GetString("CannotTransitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot transit from state {0} to state {1}:
        ///{2}.
        /// </summary>
        internal static string CannotTransitMessageForReason {
            get {
                return ResourceManager.GetString("CannotTransitMessageForReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartridge inserted into chassis #{0} cannot be read..
        /// </summary>
        internal static string CartridgeCannotBeRead {
            get {
                return ResourceManager.GetString("CartridgeCannotBeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartridge inserted.
        /// </summary>
        internal static string CartridgeInserted {
            get {
                return ResourceManager.GetString("CartridgeInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartridge Number:.
        /// </summary>
        internal static string CartridgeNumber {
            get {
                return ResourceManager.GetString("CartridgeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of cartridges:.
        /// </summary>
        internal static string CartridgesCount {
            get {
                return ResourceManager.GetString("CartridgesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartridge was inserted into chassis #{0}..
        /// </summary>
        internal static string CartridgeXInserted {
            get {
                return ResourceManager.GetString("CartridgeXInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartridge was removed from chassis #{0}..
        /// </summary>
        internal static string CartridgeXRemoved {
            get {
                return ResourceManager.GetString("CartridgeXRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassis.
        /// </summary>
        internal static string Chassis {
            get {
                return ResourceManager.GetString("Chassis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Chassis:.
        /// </summary>
        internal static string ChassisCount {
            get {
                return ResourceManager.GetString("ChassisCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassis empty.
        /// </summary>
        internal static string ChassisEmpty {
            get {
                return ResourceManager.GetString("ChassisEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassis {0}:.
        /// </summary>
        internal static string ChassisNumber {
            get {
                return ResourceManager.GetString("ChassisNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Check {
            get {
                object obj = ResourceManager.GetObject("Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        internal static string CollapseSymbol {
            get {
                return ResourceManager.GetString("CollapseSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration parameters had been changed.
        ///Click OK to save and exit, or Cancel to remain in management state..
        /// </summary>
        internal static string ConfigurationParametersChanged {
            get {
                return ResourceManager.GetString("ConfigurationParametersChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Connect {
            get {
                object obj = ResourceManager.GetObject("Connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to {0}..
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to {0} was initialized successfully..
        /// </summary>
        internal static string ConnectionOK {
            get {
                return ResourceManager.GetString("ConnectionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string ConnectTo {
            get {
                return ResourceManager.GetString("ConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption Counter:.
        /// </summary>
        internal static string ConsumptionCounter {
            get {
                return ResourceManager.GetString("ConsumptionCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Kg ({1} grams).
        /// </summary>
        internal static string ConsumptionCounterValue {
            get {
                return ResourceManager.GetString("ConsumptionCounterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have more cartridges to be corrected in this lot?.
        /// </summary>
        internal static string ContinueCorrection {
            get {
                return ResourceManager.GetString("ContinueCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correcting.....
        /// </summary>
        internal static string Correcting {
            get {
                return ResourceManager.GetString("Correcting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction failed: returning to idle state..
        /// </summary>
        internal static string CorrectionFailed {
            get {
                return ResourceManager.GetString("CorrectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction.
        /// </summary>
        internal static string CorrectionState {
            get {
                return ResourceManager.GetString("CorrectionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot communicate with burning history DB..
        /// </summary>
        internal static string DBConnectionError {
            get {
                return ResourceManager.GetString("DBConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain:.
        /// </summary>
        internal static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartridge is empty..
        /// </summary>
        internal static string EmptyCartridge {
            get {
                return ResourceManager.GetString("EmptyCartridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Lot.
        /// </summary>
        internal static string EndLot {
            get {
                return ResourceManager.GetString("EndLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot ended..
        /// </summary>
        internal static string EndOfLot {
            get {
                return ResourceManager.GetString("EndOfLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of lot was reported..
        /// </summary>
        internal static string EndOfLotReported {
            get {
                return ResourceManager.GetString("EndOfLotReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Session.
        /// </summary>
        internal static string EndSession {
            get {
                return ResourceManager.GetString("EndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution mode:.
        /// </summary>
        internal static string ExecutionMode {
            get {
                return ResourceManager.GetString("ExecutionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        internal static string ExpandSymbol {
            get {
                return ResourceManager.GetString("ExpandSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date:.
        /// </summary>
        internal static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting report to file {0}....
        /// </summary>
        internal static string ExportingToExcel {
            get {
                return ResourceManager.GetString("ExportingToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting report to excel....
        /// </summary>
        internal static string ExportReportToExcel {
            get {
                return ResourceManager.GetString("ExportReportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        internal static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report was exported to excel successfully..
        /// </summary>
        internal static string ExportToExcelSucceeded {
            get {
                return ResourceManager.GetString("ExportToExcelSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of failures:.
        /// </summary>
        internal static string FailuresCount {
            get {
                return ResourceManager.GetString("FailuresCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCB is not ready..
        /// </summary>
        internal static string FCBNotReady {
            get {
                return ResourceManager.GetString("FCBNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating report....
        /// </summary>
        internal static string FillingReport {
            get {
                return ResourceManager.GetString("FillingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find batch by.
        /// </summary>
        internal static string FindBatchBy {
            get {
                return ResourceManager.GetString("FindBatchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating report for batch {0}....
        /// </summary>
        internal static string GeneratingReport {
            get {
                return ResourceManager.GetString("GeneratingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Report.
        /// </summary>
        internal static string GetReport {
            get {
                return ResourceManager.GetString("GetReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting signed tag information....
        /// </summary>
        internal static string GetSignedTagInfo {
            get {
                return ResourceManager.GetString("GetSignedTagInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting tag serial number....
        /// </summary>
        internal static string GetTagSerialNumber {
            get {
                return ResourceManager.GetString("GetTagSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting weight to decrease....
        /// </summary>
        internal static string GetWeightToDecrease {
            get {
                return ResourceManager.GetString("GetWeightToDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware.
        /// </summary>
        internal static string Hardware {
            get {
                return ResourceManager.GetString("Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSM client path:.
        /// </summary>
        internal static string HsmClientPath {
            get {
                return ResourceManager.GetString("HsmClientPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all hardware are ready..
        /// </summary>
        internal static string HWNotReady {
            get {
                return ResourceManager.GetString("HWNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string IdleState {
            get {
                return ResourceManager.GetString("IdleState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag error occurred (error code 0x{0})..
        /// </summary>
        internal static string IdtError {
            get {
                return ResourceManager.GetString("IdtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag memory error..
        /// </summary>
        internal static string IdtError_6581 {
            get {
                return ResourceManager.GetString("IdtError_6581", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag communication error..
        /// </summary>
        internal static string IdtError_65FF {
            get {
                return ResourceManager.GetString("IdtError_65FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag synchronization was lost..
        /// </summary>
        internal static string IdtError_CC13 {
            get {
                return ResourceManager.GetString("IdtError_CC13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot send data to FCB..
        /// </summary>
        internal static string IdtError_CF0D {
            get {
                return ResourceManager.GetString("IdtError_CF0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot receive data from FCB..
        /// </summary>
        internal static string IdtError_CF0E {
            get {
                return ResourceManager.GetString("IdtError_CF0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot receive data from FCB..
        /// </summary>
        internal static string IdtError_CF0F {
            get {
                return ResourceManager.GetString("IdtError_CF0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCB initialization failed..
        /// </summary>
        internal static string IdtError_E200 {
            get {
                return ResourceManager.GetString("IdtError_E200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCB selection failed..
        /// </summary>
        internal static string IdtError_E201 {
            get {
                return ResourceManager.GetString("IdtError_E201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCB get in-place status failed..
        /// </summary>
        internal static string IdtError_E202 {
            get {
                return ResourceManager.GetString("IdtError_E202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCB select channel failed..
        /// </summary>
        internal static string IdtError_E203 {
            get {
                return ResourceManager.GetString("IdtError_E203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter was passed to FCB..
        /// </summary>
        internal static string IdtError_E204 {
            get {
                return ResourceManager.GetString("IdtError_E204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware was not initialized..
        /// </summary>
        internal static string IdtError_E205 {
            get {
                return ResourceManager.GetString("IdtError_E205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading tag public key..
        /// </summary>
        internal static string IdtError_E206 {
            get {
                return ResourceManager.GetString("IdtError_E206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal authentication failed..
        /// </summary>
        internal static string IdtError_E207 {
            get {
                return ResourceManager.GetString("IdtError_E207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed getting tag serial number..
        /// </summary>
        internal static string IdtError_E210 {
            get {
                return ResourceManager.GetString("IdtError_E210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid certificate signature..
        /// </summary>
        internal static string IdtError_E300 {
            get {
                return ResourceManager.GetString("IdtError_E300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid challenge token signature..
        /// </summary>
        internal static string IdtError_E301 {
            get {
                return ResourceManager.GetString("IdtError_E301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid certificate file..
        /// </summary>
        internal static string IdtError_E302 {
            get {
                return ResourceManager.GetString("IdtError_E302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid host public key..
        /// </summary>
        internal static string IdtError_E303 {
            get {
                return ResourceManager.GetString("IdtError_E303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter was passed to authentication..
        /// </summary>
        internal static string IdtError_E304 {
            get {
                return ResourceManager.GetString("IdtError_E304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag is blank..
        /// </summary>
        internal static string IdtError_E305 {
            get {
                return ResourceManager.GetString("IdtError_E305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge token failed..
        /// </summary>
        internal static string IdtError_E307 {
            get {
                return ResourceManager.GetString("IdtError_E307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File selection failed..
        /// </summary>
        internal static string IdtError_E308 {
            get {
                return ResourceManager.GetString("IdtError_E308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartridge was not authenticated..
        /// </summary>
        internal static string IdtError_E400 {
            get {
                return ResourceManager.GetString("IdtError_E400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid counter signature..
        /// </summary>
        internal static string IdtError_E401 {
            get {
                return ResourceManager.GetString("IdtError_E401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material overconsumption..
        /// </summary>
        internal static string IdtError_E402 {
            get {
                return ResourceManager.GetString("IdtError_E402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate random token..
        /// </summary>
        internal static string IdtError_E403 {
            get {
                return ResourceManager.GetString("IdtError_E403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter was passed to consumption update..
        /// </summary>
        internal static string IdtError_E404 {
            get {
                return ResourceManager.GetString("IdtError_E404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key generation failed..
        /// </summary>
        internal static string IdtError_E505 {
            get {
                return ResourceManager.GetString("IdtError_E505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed writing IDD..
        /// </summary>
        internal static string IdtError_E511 {
            get {
                return ResourceManager.GetString("IdtError_E511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed writing signature..
        /// </summary>
        internal static string IdtError_E512 {
            get {
                return ResourceManager.GetString("IdtError_E512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCB access error, please restart FCB..
        /// </summary>
        internal static string IdtError_FFFFFFFF {
            get {
                return ResourceManager.GetString("IdtError_FFFFFFFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Weight:.
        /// </summary>
        internal static string InitialWeight {
            get {
                return ResourceManager.GetString("InitialWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Kg.
        /// </summary>
        internal static string InitialWeightValue {
            get {
                return ResourceManager.GetString("InitialWeightValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing tag counter....
        /// </summary>
        internal static string InitTagCounter {
            get {
                return ResourceManager.GetString("InitTagCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline.
        /// </summary>
        internal static string Inline {
            get {
                return ResourceManager.GetString("Inline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-place frequency (ms):.
        /// </summary>
        internal static string InPlaceStatusInterval {
            get {
                return ResourceManager.GetString("InPlaceStatusInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password..
        /// </summary>
        internal static string InvalidUserNamePassword {
            get {
                return ResourceManager.GetString("InvalidUserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference cartridge.
        /// </summary>
        internal static string IsReference {
            get {
                return ResourceManager.GetString("IsReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if tag registration in VLL is valid....
        /// </summary>
        internal static string IsTagRegistrationValid {
            get {
                return ResourceManager.GetString("IsTagRegistrationValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot is already opened..
        /// </summary>
        internal static string LotIsAlreadyOpened {
            get {
                return ResourceManager.GetString("LotIsAlreadyOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        internal static string MaintenanceState {
            get {
                return ResourceManager.GetString("MaintenanceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing Time:.
        /// </summary>
        internal static string ManufacturingTime {
            get {
                return ResourceManager.GetString("ManufacturingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material expired..
        /// </summary>
        internal static string MaterialExpired {
            get {
                return ResourceManager.GetString("MaterialExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material ID.
        /// </summary>
        internal static string MaterialID {
            get {
                return ResourceManager.GetString("MaterialID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Type:.
        /// </summary>
        internal static string MaterialType {
            get {
                return ResourceManager.GetString("MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} material cannot be handled in chassis #{1}..
        /// </summary>
        internal static string MaterialTypeError {
            get {
                return ResourceManager.GetString("MaterialTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown material type &apos;{0}&apos;..
        /// </summary>
        internal static string MaterialTypeUndefined {
            get {
                return ResourceManager.GetString("MaterialTypeUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot was not read from Oracle DB..
        /// </summary>
        internal static string MissingLot {
            get {
                return ResourceManager.GetString("MissingLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model/Support Privileges:.
        /// </summary>
        internal static string ModelSupportPrivileges {
            get {
                return ResourceManager.GetString("ModelSupportPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new lot is read..
        /// </summary>
        internal static string NewLot {
            get {
                return ResourceManager.GetString("NewLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cartridge was burned in this lot.
        ///Burning reference cartridges is not allowed..
        /// </summary>
        internal static string NoCartridgeBurned {
            get {
                return ResourceManager.GetString("NoCartridgeBurned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that there is no cartridge left in chassis..
        /// </summary>
        internal static string NoCartridgeLeft {
            get {
                return ResourceManager.GetString("NoCartridgeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cartridges were burned in this lot.
        ///Would you still like to end this lot?.
        /// </summary>
        internal static string NoCartridgesInLot {
            get {
                return ResourceManager.GetString("NoCartridgesInLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No material info was read..
        /// </summary>
        internal static string NoMaterialInfoWasRead {
            get {
                return ResourceManager.GetString("NoMaterialInfoWasRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reference cartridges were burned in this lot.
        ///Would you still like to end this lot?.
        /// </summary>
        internal static string NoReferenceCartridgesInLot {
            get {
                return ResourceManager.GetString("NoReferenceCartridgesInLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed.
        /// </summary>
        internal static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} operation is still in process.
        ///Please wait to complete..
        /// </summary>
        internal static string OperationInProcess {
            get {
                return ResourceManager.GetString("OperationInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not allowed on cartridge {1}..
        /// </summary>
        internal static string OperationNotAllowedOnCartridge {
            get {
                return ResourceManager.GetString("OperationNotAllowedOnCartridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot file &apos;{0}&apos; is corrupted..
        /// </summary>
        internal static string OracleFileCorrupted {
            get {
                return ResourceManager.GetString("OracleFileCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read Lot from Oracle DB (file &apos;{0}&apos; does not exist)..
        /// </summary>
        internal static string OracleFileNotExists {
            get {
                return ResourceManager.GetString("OracleFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to override tag identification data?.
        /// </summary>
        internal static string OverrideTagConfirmation {
            get {
                return ResourceManager.GetString("OverrideTagConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC is busy..
        /// </summary>
        internal static string PlcIsBusy {
            get {
                return ResourceManager.GetString("PlcIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC Mode.
        /// </summary>
        internal static string PlcMode {
            get {
                return ResourceManager.GetString("PlcMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC connection was not successfully established..
        /// </summary>
        internal static string PlcNotReady {
            get {
                return ResourceManager.GetString("PlcNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC Port:.
        /// </summary>
        internal static string PlcPort {
            get {
                return ResourceManager.GetString("PlcPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC is ready..
        /// </summary>
        internal static string PlcReady {
            get {
                return ResourceManager.GetString("PlcReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC has not responded for {0} seconds: communication is lost..
        /// </summary>
        internal static string PlcTimeout {
            get {
                return ResourceManager.GetString("PlcTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to proceed?.
        /// </summary>
        internal static string ProceedMessage {
            get {
                return ResourceManager.GetString("ProceedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading batch numbers from DB....
        /// </summary>
        internal static string ReadingBatchNumbers {
            get {
                return ResourceManager.GetString("ReadingBatchNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material info of tag #{0} was verified successfully..
        /// </summary>
        internal static string ReadingEndedSuccessfully {
            get {
                return ResourceManager.GetString("ReadingEndedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed verifying tag #{0}..
        /// </summary>
        internal static string ReadingFailed {
            get {
                return ResourceManager.GetString("ReadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification of tag #{0} started....
        /// </summary>
        internal static string ReadingInProcess {
            get {
                return ResourceManager.GetString("ReadingInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report for batch {0} was generated successfully..
        /// </summary>
        internal static string ReportGeneratedSuccessfully {
            get {
                return ResourceManager.GetString("ReportGeneratedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        internal static string ReportState {
            get {
                return ResourceManager.GetString("ReportState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        internal static string Revert {
            get {
                return ResourceManager.GetString("Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string RowNumber {
            get {
                return ResourceManager.GetString("RowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending client credential....
        /// </summary>
        internal static string SendingClientCredential {
            get {
                return ResourceManager.GetString("SendingClientCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending tag counter for verification....
        /// </summary>
        internal static string SendingCounterForVerification {
            get {
                return ResourceManager.GetString("SendingCounterForVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number:.
        /// </summary>
        internal static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No session has been started..
        /// </summary>
        internal static string SessionNotStarted {
            get {
                return ResourceManager.GetString("SessionNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error signing data..
        /// </summary>
        internal static string SignatureError {
            get {
                return ResourceManager.GetString("SignatureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing VLL....
        /// </summary>
        internal static string SignVll {
            get {
                return ResourceManager.GetString("SignVll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulator.
        /// </summary>
        internal static string Simulator {
            get {
                return ResourceManager.GetString("Simulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standalone.
        /// </summary>
        internal static string Standalone {
            get {
                return ResourceManager.GetString("Standalone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        internal static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Name:.
        /// </summary>
        internal static string StationName {
            get {
                return ResourceManager.GetString("StationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Type:.
        /// </summary>
        internal static string StationType {
            get {
                return ResourceManager.GetString("StationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tag.
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag {0} is not found in VLL..
        /// </summary>
        internal static string TagNotFound {
            get {
                return ResourceManager.GetString("TagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Struct ID:.
        /// </summary>
        internal static string TagStructID {
            get {
                return ResourceManager.GetString("TagStructID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag {0} is used..
        /// </summary>
        internal static string TagUsed {
            get {
                return ResourceManager.GetString("TagUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System transitted from {0} to {1}..
        /// </summary>
        internal static string TransitionSucceeded {
            get {
                return ResourceManager.GetString("TransitionSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Uncheck {
            get {
                object obj = ResourceManager.GetObject("Uncheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cancelled..
        /// </summary>
        internal static string UserCancelled {
            get {
                return ResourceManager.GetString("UserCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        internal static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        internal static string VerificationState {
            get {
                return ResourceManager.GetString("VerificationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying....
        /// </summary>
        internal static string Verifying {
            get {
                return ResourceManager.GetString("Verifying", resourceCulture);
            }
        }
    }
}
