var xmlHelpSystemData = "";
xmlHelpSystemData += '<?xml version=\"1.0\" encoding=\"utf-8\"?>';
xmlHelpSystemData += '<WebHelpSystem DefaultUrl=\"Content/CoverPage-Help.htm\" Toc=\"Data/Toc.js\" Index=\"Data/Index.js\" Concepts=\"Data/Concepts.js\" BrowseSequence=\"Data/BrowseSequence.js\" Glossary=\"Data/Glossary.js\" SearchDatabase=\"Data/Search.js\" Alias=\"Data/Alias.xml\" Synonyms=\"Data/Synonyms.xml\" SearchFilterSet=\"Data/Filters.js\" SearchUrl=\"Content/Search.htm\" SkinName=\"HTML5-Stratasys-TopNav\" Skins=\"HTML5-PJ-Studio-TopNav,HTML5-PrinterHelp-TopNav,HTML5-slideshow,HTML5-Stratasys-01-10-15-TopNav,HTML5-Stratasys-TopNav-PreOct2015,HTML5-Stratasys-TopNav,HTML5,NewSkin\" BuildTime=\"08-Nov-15 05:22:01 PM\" BuildVersion=\"11.1.0.17275\" TargetType=\"WebHelp2\" SkinTemplateFolder=\"Skin/\" InPreviewMode=\"false\" MoveOutputContentToRoot=\"false\" MakeFileLowerCase=\"false\" UseCustomTopicFileExtension=\"false\" PreventExternalUrls=\"false\" EnableResponsiveOutput=\"true\" IncludeGlossarySearchResults=\"true\" ResultsPerPage=\"20\">';
xmlHelpSystemData += '    <CatapultSkin Version=\"2\" SkinType=\"WebHelp2\" ComponentType=\"MasterPage\" TemplateName=\"Fluid\" Comment=\"HTML5 Top Navigation skin\" EnableResponsiveOutput=\"True\" Name=\"HTML5-PJ-Studio-TopNav\">';
xmlHelpSystemData += '        <WebHelpOptions NavigationPanePosition=\"Right\" TopMenuDepth=\"4\" />';
xmlHelpSystemData += '    </CatapultSkin>';
xmlHelpSystemData += '    <CatapultSkin Version=\"2\" SkinType=\"WebHelp2\" ComponentType=\"MasterPage\" TemplateName=\"Fluid\" Comment=\"HTML5 Top Navigation skin\" EnableResponsiveOutput=\"True\" Name=\"HTML5-PrinterHelp-TopNav\">';
xmlHelpSystemData += '        <WebHelpOptions NavigationPanePosition=\"Right\" />';
xmlHelpSystemData += '    </CatapultSkin>';
xmlHelpSystemData += '    <CatapultSkin Version=\"2\" SkinType=\"WebHelp2\" Comment=\"HTML5 skin\" Anchors=\"Width,Height\" Width=\"800\" Height=\"600\" Top=\"0\" Left=\"0\" Bottom=\"0\" Right=\"0\" Tabs=\"\" DefaultTab=\"TOC\" UseBrowserDefaultSize=\"true\" UseDefaultBrowserSetup=\"True\" EnableResponsiveOutput=\"True\" DisplayCommunitySearchResults=\"false\" DisplayNotificationOptions=\"false\" AutoSyncTOC=\"true\" CommentsInTopic=\"false\" DisplaySearchBar=\"false\" Name=\"HTML5-slideshow\">';
xmlHelpSystemData += '        <WebHelpOptions NavigationPaneWidth=\"0\" HideNavigationOnStartup=\"true\" />';
xmlHelpSystemData += '        <Toolbar EnableCustomLayout=\"true\" Buttons=\"\">';
xmlHelpSystemData += '            <Script>$(document).ready(function(){';
xmlHelpSystemData += '   $(\'head\').append(\'&lt;link rel=\"shortcut icon\" href=\"Content/Resources/Images/favicon.ico\" type=\"image/x-icon\" /&gt;\');';
xmlHelpSystemData += '});</Script>';
xmlHelpSystemData += '        </Toolbar>';
xmlHelpSystemData += '    </CatapultSkin>';
xmlHelpSystemData += '    <CatapultSkin Version=\"2\" SkinType=\"WebHelp2\" ComponentType=\"MasterPage\" TemplateName=\"Fluid\" Comment=\"HTML5 Top Navigation skin\" EnableResponsiveOutput=\"True\" Name=\"HTML5-Stratasys-01-10-15-TopNav\">';
xmlHelpSystemData += '        <WebHelpOptions NavigationPanePosition=\"Right\" TopMenuDepth=\"4\" />';
xmlHelpSystemData += '    </CatapultSkin>';
xmlHelpSystemData += '    <CatapultSkin Version=\"2\" SkinType=\"WebHelp2\" ComponentType=\"MasterPage\" TemplateName=\"Fluid\" Comment=\"HTML5 Top Navigation skin\" EnableResponsiveOutput=\"True\" Name=\"HTML5-Stratasys-TopNav-PreOct2015\">';
xmlHelpSystemData += '        <WebHelpOptions NavigationPanePosition=\"Right\" TopMenuDepth=\"4\" />';
xmlHelpSystemData += '    </CatapultSkin>';
xmlHelpSystemData += '    <CatapultSkin Version=\"2\" SkinType=\"WebHelp2\" ComponentType=\"MasterPage\" TemplateName=\"Fluid\" Comment=\"HTML5 Top Navigation skin\" EnableResponsiveOutput=\"True\" Name=\"HTML5-Stratasys-TopNav\">';
xmlHelpSystemData += '        <WebHelpOptions NavigationPanePosition=\"Right\" TopMenuDepth=\"4\" />';
xmlHelpSystemData += '    </CatapultSkin>';
xmlHelpSystemData += '    <CatapultSkin Version=\"2\" SkinType=\"WebHelp2\" Comment=\"HTML5 skin\" Anchors=\"Width,Height\" Width=\"800\" Height=\"600\" Top=\"0\" Left=\"0\" Bottom=\"0\" Right=\"0\" Tabs=\"TOC,Community\" DefaultTab=\"TOC\" UseBrowserDefaultSize=\"true\" UseDefaultBrowserSetup=\"True\" EnableResponsiveOutput=\"True\" DisplayCommunitySearchResults=\"false\" DisplayNotificationOptions=\"false\" AutoSyncTOC=\"true\" CommentsInTopic=\"false\" Name=\"HTML5\">';
xmlHelpSystemData += '        <WebHelpOptions NavigationPaneWidth=\"285\" />';
xmlHelpSystemData += '        <Toolbar EnableCustomLayout=\"true\" Buttons=\"Print|RemoveHighlight|Separator|Separator|Filler|PreviousTopic|CurrentTopicIndex|NextTopic\">';
xmlHelpSystemData += '            <Script>$(document).ready(function(){';
xmlHelpSystemData += '   $(\'head\').append(\'&lt;link rel=\"shortcut icon\" href=\"Content/Resources/Images/favicon.ico\" type=\"image/x-icon\" /&gt;\');';
xmlHelpSystemData += '});</Script>';
xmlHelpSystemData += '        </Toolbar>';
xmlHelpSystemData += '    </CatapultSkin>';
xmlHelpSystemData += '    <CatapultSkin Version=\"2\" SkinType=\"WebHelp2\" ComponentType=\"MasterPage\" TemplateName=\"Fluid\" Comment=\"HTML5 Top Navigation skin\" EnableResponsiveOutput=\"True\" Name=\"NewSkin\">';
xmlHelpSystemData += '        <WebHelpOptions NavigationPanePosition=\"Right\" />';
xmlHelpSystemData += '    </CatapultSkin>';
xmlHelpSystemData += '</WebHelpSystem>';
MadCap.Utilities.Xhr._FilePathToXmlStringMap.Add('HelpSystem', xmlHelpSystemData);
