//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.BSP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CBS.BSP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is null..
        /// </summary>
        internal static string ArgumentNullMessage {
            get {
                return ResourceManager.GetString("ArgumentNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session with {0} ended..
        /// </summary>
        internal static string BsaSessionEnded {
            get {
                return ResourceManager.GetString("BsaSessionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session with {0} started..
        /// </summary>
        internal static string BsaSessionStarted {
            get {
                return ResourceManager.GetString("BsaSessionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building signed IDD and send to {0}....
        /// </summary>
        internal static string BuildingSignedIDD {
            get {
                return ResourceManager.GetString("BuildingSignedIDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot decrypt HSM password..
        /// </summary>
        internal static string CannotDecryptHsmPassword {
            get {
                return ResourceManager.GetString("CannotDecryptHsmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside Secure public key cannot be loaded..
        /// </summary>
        internal static string CannotLoadISPublicKey {
            get {
                return ResourceManager.GetString("CannotLoadISPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuing a closed Lot..
        /// </summary>
        internal static string ContinueClosedLot {
            get {
                return ResourceManager.GetString("ContinueClosedLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuing an open Lot..
        /// </summary>
        internal static string ContinueOpenedLot {
            get {
                return ResourceManager.GetString("ContinueOpenedLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter value of tag #{0} is unverified..
        /// </summary>
        internal static string CounterValueUnverified {
            get {
                return ResourceManager.GetString("CounterValueUnverified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter value of tag #{0} is verified..
        /// </summary>
        internal static string CounterValueVerified {
            get {
                return ResourceManager.GetString("CounterValueVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decremental value {0} was sent to {1}..
        /// </summary>
        internal static string DecrementValueSentToBSA {
            get {
                return ResourceManager.GetString("DecrementValueSentToBSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (error code {0}).
        /// </summary>
        internal static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting public key from HSM..
        /// </summary>
        internal static string ErrorGettingPublicKey {
            get {
                return ResourceManager.GetString("ErrorGettingPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred, connection is faulted:.
        /// </summary>
        internal static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading configuration file, use default values instead..
        /// </summary>
        internal static string ErrorReadingConfig {
            get {
                return ResourceManager.GetString("ErrorReadingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error signing data with HSM..
        /// </summary>
        internal static string ErrorSigningData {
            get {
                return ResourceManager.GetString("ErrorSigningData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to DB..
        /// </summary>
        internal static string FailedConnectingToDB {
            get {
                return ResourceManager.GetString("FailedConnectingToDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed initializing HSM client..
        /// </summary>
        internal static string FailedInitializingHsmClient {
            get {
                return ResourceManager.GetString("FailedInitializingHsmClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting public key:.
        /// </summary>
        internal static string GettingPublicKey {
            get {
                return ResourceManager.GetString("GettingPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSM client was initialized successfully..
        /// </summary>
        internal static string HsmClientInitializedSuccessfully {
            get {
                return ResourceManager.GetString("HsmClientInitializedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSM library &apos;{0}&apos; was not found..
        /// </summary>
        internal static string HsmLibNotFound {
            get {
                return ResourceManager.GetString("HsmLibNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSM library was loaded successfully..
        /// </summary>
        internal static string HsmLoadedSuccessfully {
            get {
                return ResourceManager.GetString("HsmLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSM client was not successfully initialized..
        /// </summary>
        internal static string HsmNotInitialized {
            get {
                return ResourceManager.GetString("HsmNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing HSM client....
        /// </summary>
        internal static string InitializingHsmClient {
            get {
                return ResourceManager.GetString("InitializingHsmClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting tag {0} to DB....
        /// </summary>
        internal static string InsertingTagToDB {
            get {
                return ResourceManager.GetString("InsertingTagToDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB record of tag {0} is corrupted..
        /// </summary>
        internal static string InvalidTag {
            get {
                return ResourceManager.GetString("InvalidTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDF does not match existing Lot..
        /// </summary>
        internal static string LdfMismatch {
            get {
                return ResourceManager.GetString("LdfMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading LDF....
        /// </summary>
        internal static string LdfRead {
            get {
                return ResourceManager.GetString("LdfRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading HSM library....
        /// </summary>
        internal static string LoadingHsm {
            get {
                return ResourceManager.GetString("LoadingHsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Vault IC list file &apos;{0}&apos;:.
        /// </summary>
        internal static string LoadingList {
            get {
                return ResourceManager.GetString("LoadingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading tag {0} with public key {1} to DB....
        /// </summary>
        internal static string LoadingTagToDB {
            get {
                return ResourceManager.GetString("LoadingTagToDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot file was not loaded..
        /// </summary>
        internal static string LotNotFound {
            get {
                return ResourceManager.GetString("LotNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to material info version number: {0}, material ID: {1}, model/support: {2}, manufacturing Time: {3}, batch number: {4}, initial weight: {5}, expiration Date: {6}.
        /// </summary>
        internal static string MaterialInfoDetails {
            get {
                return ResourceManager.GetString("MaterialInfoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; directory was not found..
        /// </summary>
        internal static string OracleDirectoryNotFound {
            get {
                return ResourceManager.GetString("OracleDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid file was found in Oracle folder..
        /// </summary>
        internal static string OracleFileNotFound {
            get {
                return ResourceManager.GetString("OracleFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key: &apos;{0}&apos;.
        /// </summary>
        internal static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag serial number &apos;{0}&apos; was received from {1}..
        /// </summary>
        internal static string SerialNumberReceived {
            get {
                return ResourceManager.GetString("SerialNumberReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature: &apos;{0}&apos;.
        /// </summary>
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing message &apos;{0}&apos;:.
        /// </summary>
        internal static string SigningMessage {
            get {
                return ResourceManager.GetString("SigningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting a new Lot..
        /// </summary>
        internal static string StartNewLot {
            get {
                return ResourceManager.GetString("StartNewLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag {0} was found in DB; tag status: {1}..
        /// </summary>
        internal static string TagFoundInDB {
            get {
                return ResourceManager.GetString("TagFoundInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, serial number: {1}, current tag weight: {2}.
        /// </summary>
        internal static string TagInfoDetails {
            get {
                return ResourceManager.GetString("TagInfoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag {0} is already used..
        /// </summary>
        internal static string TagIsUsed {
            get {
                return ResourceManager.GetString("TagIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag {0} was not found in VLL..
        /// </summary>
        internal static string TagNotFound {
            get {
                return ResourceManager.GetString("TagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating DB..
        /// </summary>
        internal static string UpdatingDB {
            get {
                return ResourceManager.GetString("UpdatingDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; is not allowed to access central burning server..
        /// </summary>
        internal static string UserNotAllowed {
            get {
                return ResourceManager.GetString("UserNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; requests for SSYS public key....
        /// </summary>
        internal static string UserRequests {
            get {
                return ResourceManager.GetString("UserRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying message &apos;{0}&apos; with signature &apos;{1}&apos;....
        /// </summary>
        internal static string VerfyingMessage {
            get {
                return ResourceManager.GetString("VerfyingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vll service ended..
        /// </summary>
        internal static string VllEnded {
            get {
                return ResourceManager.GetString("VllEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLL service started..
        /// </summary>
        internal static string VllStarted {
            get {
                return ResourceManager.GetString("VllStarted", resourceCulture);
            }
        }
    }
}
