//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.VLLA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CBS.VLLA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLL.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminating conflicts with existing records....
        /// </summary>
        internal static string EliminatingConflicts {
            get {
                return ResourceManager.GetString("EliminatingConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VaultIC list loading started....
        /// </summary>
        internal static string LoadingStarted {
            get {
                return ResourceManager.GetString("LoadingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled..
        /// </summary>
        internal static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing VaultIC list....
        /// </summary>
        internal static string ParsingList {
            get {
                return ResourceManager.GetString("ParsingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags were already loaded.
        ///Would you like to reload them?.
        /// </summary>
        internal static string TagsLoadedConfirmMessage {
            get {
                return ResourceManager.GetString("TagsLoadedConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags are used..
        /// </summary>
        internal static string TagsUsed {
            get {
                return ResourceManager.GetString("TagsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tags were found on list:
        ///{1} tags were loaded successfully to DB.
        ///{2} tags were found in DB marked as new.
        ///{3} tags were found in DB marked as used..
        /// </summary>
        internal static string VllLoadingCompleted {
            get {
                return ResourceManager.GetString("VllLoadingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading tag {0}:
        ///{1} out of {2} tags were loaded successfully..
        /// </summary>
        internal static string VllLoadingProgress {
            get {
                return ResourceManager.GetString("VllLoadingProgress", resourceCulture);
            }
        }
    }
}
