/* --------------------------------------------------------------------------
 * VaultIC API
 * Copyright (C) Inside Secure, 2011. All Rights Reserved.
 * -------------------------------------------------------------------------- */

/**
 * \file vaultic_err.h
 * 
 * \brief Errors returned by the VaultIC API.
 * 
 * \par Description:
 * This file enumerates all errors returned by the VaultIC API. Unique error
 * codes are provided for every possible failure case.
 */

#ifndef VAULTIC_ERR_H
#define VAULTIC_ERR_H

#define VLT_ERROR( module, errorcode ) ((VLT_U16)((module) + (errorcode)))

/*
* Module Error codes 
*/
#define VLT_GLOBAL      0xC000
#define VLT_COMMS       0xC100
#define VLT_API         0xC200
#define VLT_API2        0xC300
#define VLT_DES         0xC400
#define VLT_TDES        0xC500
#define VLT_CIPHER      0xC600
#define VLT_PADDING     0xC700
#define VLT_ISO7816     0xC800
#define VLT_SIGNER      0xC900
#define VLT_SECCHAN     0xCA00
#define VLT_SCP02       0xCB00
#define VLT_BLKPTCL     0xCC00
#define VLT_PTCL        0xCD00
#define VLT_SPI         0xCE00
#define VLT_TWI         0xCF00
#define VLT_AES         0xD000
#define VLT_SCP03       0xD100
#define VLT_AES_CMAC    0xD200
#define VLT_ISO9797_MAC 0xD300
#define VLT_KEY_WRAP    0xD400
#define VLT_MS_AUTH     0xD500
#define VLT_AARDVARK    0xD600
#define VLT_CHEETAH     0xD700
#define VLT_ID_AUTH     0xD800
#define VLT_FILE_SYS    0xD900
#define VLT_MEM         0xDA00
#define VLT_CRC16       0xDB00
#define VLT_ID_AUTH2    0xDC00
#define VLT_STRONG_AUTH 0xDD00
#define VLT_CRYPTO      0xDE00
#define VLT_ECDSA       0xDF00

/*
* Global Error Codes
*/
/**
 * \def VLT_OK
 * \addgroup Constants
 * \brief Denotes successful completion of an API call.
 */
#define VLT_OK              VLT_ERROR( VLT_GLOBAL, 0 )
/**
 * \def VLT_FAIL
 * \addgroup Constants
 * \brief Denotes generic failure of an API call.
 */
#define VLT_FAIL            VLT_ERROR( VLT_GLOBAL, 1 )
/**
 * \def VLT_EOF
 * \addgroup Constants
 * \brief Denotes the end of a file being reached.
 */
#define VLT_EOF             VLT_ERROR( VLT_GLOBAL, 2 )
/**
 * \def EMETHODNOTSUPPORTED
 * \addgroup Constants
 * \brief Denotes the API method call is not supported.
 */
#define EMETHODNOTSUPPORTED VLT_ERROR( VLT_GLOBAL, 3 )


/**
 * API Error Codes
 */
#define ESPNULLPARA         VLT_ERROR( VLT_API, 0 )
#define EMADPASSLENIVLD     VLT_ERROR( VLT_API, 1 )
#define EMADMSPKEYSINVLD    VLT_ERROR( VLT_API, 2 )
#define EMADSCPKEYSINVLD    VLT_ERROR( VLT_API, 3 )
#define ESPPASSLENIVLD      VLT_ERROR( VLT_API, 4 )
#define EEAIVLDCRPTLEN      VLT_ERROR( VLT_API, 5 )
#define EGIAIVLDSIGLEN      VLT_ERROR( VLT_API, 6 )
#define EIUNULLPARA         VLT_ERROR( VLT_API, 10 )
#define EIUBADSCP           VLT_ERROR( VLT_API, 11 )
#define ESETCNFGNULLDATA    VLT_ERROR( VLT_API, 12 )
#define ESETCNFGIVLDAARLEN  VLT_ERROR( VLT_API, 13 )
#define ESETCNFGIVLDDTLEN   VLT_ERROR( VLT_API, 14 )
#define ESETCNFGIVLDI2CLEN  VLT_ERROR( VLT_API, 15 )
#define ESETCNFGIVLDITEM    VLT_ERROR( VLT_API, 16 )
#define EGEAINVLDHOSTCHLEN  VLT_ERROR( VLT_API, 17 )
#define EGEAINVLDHOSTSIGLEN VLT_ERROR( VLT_API, 18 )
#define ELFNOROOM           VLT_ERROR( VLT_API, 19 )
#define EEANULLPARA         VLT_ERROR( VLT_API, 20 )
#define EEABADCHAN          VLT_ERROR( VLT_API, 21 )
#define ELFNULLPARAM        VLT_ERROR( VLT_API, 22 )
#define ELFIVLDRESPLEN      VLT_ERROR( VLT_API, 23 )
#define ERFNULLPARAM        VLT_ERROR( VLT_API, 24 )
#define ERFINVLDLEN         VLT_ERROR( VLT_API, 25 )
#define ERFLENEXDMAXSZ      VLT_ERROR( VLT_API, 26 )
#define ESETCNFGIVLDSPILEN  VLT_ERROR( VLT_API, 27 )
#define EWFIVLDLEN          VLT_ERROR( VLT_API, 28 )
#define EGRNULLPARAM        VLT_ERROR( VLT_API, 29 )
#define EMADNULLPARA        VLT_ERROR( VLT_API, 30 )
#define EMADBADOPER         VLT_ERROR( VLT_API, 31 )
#define EGRNOROOM           VLT_ERROR( VLT_API, 32 )
#define ETC2NULLPARAM       VLT_ERROR( VLT_API, 33 )
#define ETC2NOROOM          VLT_ERROR( VLT_API, 34 )
#define ESFDINVLDPATHLEN    VLT_ERROR( VLT_API, 35 )
#define EENINVLDPLTXTLEN    VLT_ERROR( VLT_API, 36 )
#define EDCINVLDCHPTXTLEN   VLT_ERROR( VLT_API, 37 )
#define ETC3INVLDLEN        VLT_ERROR( VLT_API, 38 )
#define ETC4IVLDSENDLEN     VLT_ERROR( VLT_API, 39 )
#define ETC4IVLDRECVLEN     VLT_ERROR( VLT_API, 40 )
#define EGAINULLPARA        VLT_ERROR( VLT_API, 41 )
#define EVSINVLDMSGLEN      VLT_ERROR( VLT_API, 42 )
#define EVSINVLDSIGLEN      VLT_ERROR( VLT_API, 43 )
#define EVSINVLDSTATECFG    VLT_ERROR( VLT_API, 44 )
#define EVSINVLDSTATESND    VLT_ERROR( VLT_API, 45 )
#define EGTLBINFIVLDPTR     VLT_ERROR( VLT_API, 46 )
#define EGASIVLDLEN         VLT_ERROR( VLT_API, 47 )
#define EMDINVLDMSGLEN      VLT_ERROR( VLT_API, 48 )
#define EMDINVLDSGSTLEN     VLT_ERROR( VLT_API, 49 )
#define EMDIVLDSTATE        VLT_ERROR( VLT_API, 50 )
#define ERDGPIONULLPARAM    VLT_ERROR( VLT_API, 51 )
#define ERKSCIVLDCRC        VLT_ERROR( VLT_API, 52 )
#define ERKHOTPIVLDCRC      VLT_ERROR( VLT_API, 53 )
#define ERKTOTPIVLDCRC      VLT_ERROR( VLT_API, 54 )
#define ERKRSAPBIVLDCRC     VLT_ERROR( VLT_API, 55 )
#define ERKRSAPRIVLDCRC     VLT_ERROR( VLT_API, 56 )
#define ERKRSACRIVLDCRC     VLT_ERROR( VLT_API, 57 )    
#define ERKDSAPBIVLDCRC     VLT_ERROR( VLT_API, 58 )
#define ERKDSAPRIVLDCRC     VLT_ERROR( VLT_API, 59 )
#define ERKECDSAPBIVLDCRC   VLT_ERROR( VLT_API, 60 )
#define ERKECDSAPRIVLDCRC   VLT_ERROR( VLT_API, 61 )
#define EGCNULLPARA         VLT_ERROR( VLT_API, 62 )
#define ERKRAWNOROOM        VLT_ERROR( VLT_API, 63 )
#define EGTDEVSIVLDPARAM    VLT_ERROR( VLT_API, 64 )
#define EGTDEVSIVLDSTR      VLT_ERROR( VLT_API, 65 )
#define EGTDEVSINSFLEN      VLT_ERROR( VLT_API, 66 )
#define ERKIDNULLPARA       VLT_ERROR( VLT_API, 67 )
#define ERKIDBADFIELD       VLT_ERROR( VLT_API, 68 )
#define ERKIDNOROOM         VLT_ERROR( VLT_API, 69 )
#define ERKIDIVLDCRC        VLT_ERROR( VLT_API, 70 )
#define EGIANULLPARA        VLT_ERROR( VLT_API, 71 )
#define EGIANOROOM          VLT_ERROR( VLT_API, 72 )
#define ERKDSAPARAMSNULLPARA    VLT_ERROR( VLT_API, 73 ) 
#define ERKDSAPARAMSBADFIELD    VLT_ERROR( VLT_API, 74 )
#define ERKDSAPARAMSIVLDCRC     VLT_ERROR( VLT_API, 75 )
#define ERKECDSAPARAMSNULLPARA  VLT_ERROR( VLT_API, 76 )
#define ERKECDSAPARAMSBADFIELD  VLT_ERROR( VLT_API, 77 )
#define ERKECDSAPARAMSNOROOM    VLT_ERROR( VLT_API, 78 )
#define ERKECDSAPARAMSIVLDCRC   VLT_ERROR( VLT_API, 79 )
#define EGEANULLPARA        VLT_ERROR( VLT_API, 80 )
#define ERKKEYGENNULLPARA   VLT_ERROR( VLT_API, 81 )
#define ERKKEYGENNODATA     VLT_ERROR( VLT_API, 82 )
#define ERKKEYGENIVLDCRC    VLT_ERROR( VLT_API, 83 )
#define EGRZEROBYTES        VLT_ERROR( VLT_API, 84 )
#define ETC2ZEROBYTES       VLT_ERROR( VLT_API, 85 )
#define ERFZEROBYTES        VLT_ERROR( VLT_API, 86 )
#define ERFNOROOM           VLT_ERROR( VLT_API, 87 )

#define EIANULLPARA         VLT_ERROR( VLT_API, 90 )
#define EIABADALGO          VLT_ERROR( VLT_API, 91 )
#define EPKNULLPARA         VLT_ERROR( VLT_API, 100 )
#define ERKNULLPARA         VLT_ERROR( VLT_API, 110 )
#define ERKMISMATCH         VLT_ERROR( VLT_API, 112 )
#define ERKNOROOM           VLT_ERROR( VLT_API, 113 )
#define ERKUNSUPPKEY        VLT_ERROR( VLT_API, 114 )
#define EGSNULLPARA         VLT_ERROR( VLT_API, 150 )
#define EVSNULLPARA         VLT_ERROR( VLT_API, 160 )
#define EGASNULLPARA        VLT_ERROR( VLT_API, 170 )
#define EGASNOROOM          VLT_ERROR( VLT_API, 171 )
#define EMDNULLPARA         VLT_ERROR( VLT_API, 180 )
#define EMDNOROOM           VLT_ERROR( VLT_API, 181 )
#define EGKPNULLPARA        VLT_ERROR( VLT_API, 200 )
#define EGKPBADKPG          VLT_ERROR( VLT_API, 201 )
#define ESFNULLPARA         VLT_ERROR( VLT_API, 230 )
#define ESFEXPSUC           VLT_ERROR( VLT_API, 231 )
#define EC4NULLPARA         VLT_ERROR( VLT_API, 130 )
#define EC4NOROOM           VLT_ERROR( VLT_API, 131 )
#define EC1NULLPARA         VLT_ERROR( VLT_API, 140 )
#define EPKBADFIELDRSACRT   VLT_ERROR( VLT_API, 101 )
#define ERKINVLDRSP         VLT_ERROR( VLT_API, 111 )
#define ERKBADFIELD         VLT_ERROR( VLT_API, 115 )
#define EPKBADFLDECDSAPUB   VLT_ERROR( VLT_API, 116 )
#define EIAOAEPNULLPARA     VLT_ERROR( VLT_API, 117 )



#define ERKRAWNULLPARA      VLT_ERROR( VLT_API, 240 )
#define ERKSECNULLPARA      VLT_ERROR( VLT_API, 241 )
#define ERKHPNULLPARA       VLT_ERROR( VLT_API, 242 )
#define ERKTPNULLPARA       VLT_ERROR( VLT_API, 243 )
#define ERKRPUBNULLPARA     VLT_ERROR( VLT_API, 244 )
#define ERKRPRIVNULLPARA    VLT_ERROR( VLT_API, 245 )
#define ERKRCRTNULLPARA     VLT_ERROR( VLT_API, 246 )
#define ERKDPUBNULLPARA     VLT_ERROR( VLT_API, 247 )
#define ERKDPRIVNULLPARA    VLT_ERROR( VLT_API, 248 )
#define ERKEPUBNULLPARA     VLT_ERROR( VLT_API, 249 )
#define ERKEPRIVNULLPARA    VLT_ERROR( VLT_API, 250 )
#define ERKSECNOROOM        VLT_ERROR( VLT_API, 251 )
#define ERKHPNOROOM         VLT_ERROR( VLT_API, 252 )
#define ERKTPNOROOM         VLT_ERROR( VLT_API, 253 )
#define ERKRPUBNOROOM       VLT_ERROR( VLT_API, 254 )
#define ERKRPRIVNOROOM      VLT_ERROR( VLT_API, 255 )
#define ERKRCRTNOROOM       VLT_ERROR( VLT_API, 256 )
#define ERKDPUBNOROOM       VLT_ERROR( VLT_API, 257 )
#define ERKDPRIVNOROOM      VLT_ERROR( VLT_API, 258 )
#define ERKEPUBNOROOM       VLT_ERROR( VLT_API, 259 )
#define ERKEPRIVNOROOM      VLT_ERROR( VLT_API, 260 )
#define ERKCMDNULLPARA      VLT_ERROR( VLT_API, 261 )
#define EPKEPRIVNULLPARA    VLT_ERROR( VLT_API, 262 )
#define EPKEPUBNULLPARA     VLT_ERROR( VLT_API, 263 )
#define EPKDPRIVNULLPARA    VLT_ERROR( VLT_API, 264 )
#define EPKDPUBNULLPARA     VLT_ERROR( VLT_API, 265 )
#define EPKRCRTNULLPARA     VLT_ERROR( VLT_API, 266 )
#define EPKRPUBNULLPARA     VLT_ERROR( VLT_API, 267 )
#define EPKTPNULLPARA       VLT_ERROR( VLT_API, 268 )
#define EPKRAWNULLPARA      VLT_ERROR( VLT_API, 267 )
#define EPKHPNULLPARA       VLT_ERROR( VLT_API, 268 )
#define EPKDSAPARAMNULLPARA VLT_ERROR( VLT_API, 269 )
#define EPKECDSAPRMNULLPARA VLT_ERROR( VLT_API, 270 )
#define EPKIDNULLPARA       VLT_ERROR( VLT_API, 271 )
#define EGASINVLDLEN        VLT_ERROR( VLT_API, 272 )
#define EGAINVLDRECLEN      VLT_ERROR( VLT_API, 273 )
#define ESETCNFGIVLDCOMMLEN VLT_ERROR( VLT_API, 274 )
#define ESETCNFGIVLDGPIOLEN VLT_ERROR( VLT_API, 275 )
#define ESETCNFGIVLDUSBMAXLEN	VLT_ERROR( VLT_API, 276 )
#define EGETCHALLENGENULLDATA	VLT_ERROR( VLT_API, 277 )
#define EGETCHALLENGEINVLENGTH	VLT_ERROR( VLT_API, 278 )
#define EDEACTIVATENULLDATA		VLT_ERROR( VLT_API, 279 )
#define EDEACTIVATEINVLENGTH	VLT_ERROR( VLT_API, 280 )
#define EICNULLPARAM			VLT_ERROR( VLT_API, 281 )
#define EICINVLDLEN				VLT_ERROR( VLT_API, 282 )
#define EICINVLDVAL				VLT_ERROR( VLT_API, 283 )
#define ESETCNTNULLDATA			VLT_ERROR( VLT_API, 284 )
#define ESETCNTINVLDLEN			VLT_ERROR( VLT_API, 285 )
#define ESETCNTINVLDVAL			VLT_ERROR( VLT_API, 286 )
#define EDCNULLPARAM			VLT_ERROR( VLT_API, 287 )
#define EDCINVLDLEN				VLT_ERROR( VLT_API, 288 )
#define EDCINVLDVAL				VLT_ERROR( VLT_API, 289 )

/**
 * API 2 Error Codes 
 */
#define ECFNULLPARA         VLT_ERROR( VLT_API2, 10 )
#define EIUINVLDPARAM       VLT_ERROR( VLT_API2, 11 )
#define EGCINVLDDEVIDPTH    VLT_ERROR( VLT_API2, 12 )
#define EGCINVLDHSTIDPTH    VLT_ERROR( VLT_API2, 13 )
#define EGCDATATOOLRG       VLT_ERROR( VLT_API2, 14 )
#define EIADATATOOLRG       VLT_ERROR( VLT_API2, 15 )
#define ECFILNMLENTOOBIG    VLT_ERROR( VLT_API2, 16 )
#define ECFOLNMLENTOOBIG    VLT_ERROR( VLT_API2, 17 )
#define ECFLINVLDLEN        VLT_ERROR( VLT_API2, 18 )
#define ECFINVLDLEN         VLT_ERROR( VLT_API2, 19 )
#define ECFLNULLPARA        VLT_ERROR( VLT_API2, 20 )
#define EWFNULLPARA         VLT_ERROR( VLT_API2, 40 )
#define EWFTOOBIG           VLT_ERROR( VLT_API2, 41 )
#define ESANULLPARA         VLT_ERROR( VLT_API2, 90 )
#define ESPVNULLPARA        VLT_ERROR( VLT_API2, 91 )
#define EGINULLPARA         VLT_ERROR( VLT_API2, 100 )
#define ESTNULLPARA         VLT_ERROR( VLT_API2, 110 )
#define EGTINFOIVLDRESPLEN  VLT_ERROR( VLT_API2, 111 )
#define ESCNULLPARA         VLT_ERROR( VLT_API2, 130 )
#define EENULLPARA          VLT_ERROR( VLT_API2, 140 )
#define EDNULLPARA          VLT_ERROR( VLT_API2, 150 )
#define ETC3NULLPARA        VLT_ERROR( VLT_API2, 160 )
#define ETC3TOOBIG          VLT_ERROR( VLT_API2, 161 )
#define ETC4NULLPARA        VLT_ERROR( VLT_API2, 170 )
#define ETC4TOOBIG          VLT_ERROR( VLT_API2, 171 )
#define ETC4NOROOM          VLT_ERROR( VLT_API2, 172 )
#define EGPDNULLPARA        VLT_ERROR( VLT_API2, 180 )
#define EGPWNULLPARA        VLT_ERROR( VLT_API2, 190 )
#define EGPRNULLPARA        VLT_ERROR( VLT_API2, 200 )
#define EC2NULLPARA         VLT_ERROR( VLT_API2, 30 )
#define EC2TOOBIG           VLT_ERROR( VLT_API2, 31 )
#define EC2ANULLPARA        VLT_ERROR( VLT_API2, 60 )
#define EC2ANOROOM          VLT_ERROR( VLT_API2, 61 )
#define EC2AINVLDRSP        VLT_ERROR( VLT_API2, 62 )
#define EGTBADSW            VLT_ERROR( VLT_API2, 211 )
#define EGTINVLDSWSZ        VLT_ERROR( VLT_API2, 210 )
#define ECINVLDSWSZ         VLT_ERROR( VLT_API2, 220 )
#define ECINVLDRSP          VLT_ERROR( VLT_API2, 221 )
#define EICIVLDRESPLEN		VLT_ERROR( VLT_API2, 222 )
/**
 * Secure Channel Generic (SCP) 
 */
#define ESCPINITNULLPARAM           VLT_ERROR( VLT_SECCHAN, 0 )
#define ESCPINITUPDTMODE            VLT_ERROR( VLT_SECCHAN, 1 )
#define ESCPGENRANDFAIL             VLT_ERROR( VLT_SECCHAN, 2 )
#define ESCPINITUPDTFAIL            VLT_ERROR( VLT_SECCHAN, 3 )
#define SCPGETSTATENULLPARAM        VLT_ERROR( VLT_SECCHAN, 4 )

/*
* Secure Channel SCP02 specific
*/
#define ESCP02INITNULLPARAM         VLT_ERROR( VLT_SCP02, 0 )
#define ESCP02INVLDDEVCRYPTO        VLT_ERROR( VLT_SCP02, 1 )
#define ESCP02WRAPNULLPARAM         VLT_ERROR( VLT_SCP02, 2 )
#define ESCP02UNWRAPNULLPARAM       VLT_ERROR( VLT_SCP02, 3 )
#define ESCP02ADDMACNULLPARAM       VLT_ERROR( VLT_SCP02, 4 )
#define ESCP02DERSESSKEYNULLPARAM   VLT_ERROR( VLT_SCP02, 5 )
#define ESCP02TDESEDECBCNP          VLT_ERROR( VLT_SCP02, 6 )
#define ESCP02ISO9797MACALGO1       VLT_ERROR( VLT_SCP02, 7 )
#define ESCP02UPDTCMACIV            VLT_ERROR( VLT_SCP02, 8 )
#define ESCP02ENCCMDDATANULLPARAM   VLT_ERROR( VLT_SCP02, 9 )
#define ESCP02CALCMACINVLDMODE      VLT_ERROR( VLT_SCP02, 10 )
#define ESCP02DECCMDDATANULLPARAM   VLT_ERROR( VLT_SCP02, 11 )
#define ESCP02INVLDRMAC             VLT_ERROR( VLT_SCP02, 12 )
#define ESCP02INVLDCMAC             VLT_ERROR( VLT_SCP02, 13 )
#define ESCP02EXTAUTHFAIL           VLT_ERROR( VLT_SCP02, 14 )
#define ESCP02GETOVHDNULLPARAM      VLT_ERROR( VLT_SCP02, 15 )
#define ESCP02GETOVHDINVLDMODE      VLT_ERROR( VLT_SCP02, 16 )
#define ESCP02INITINVLDSMAC         VLT_ERROR( VLT_SCP02, 17 )
#define ESCP02INITINVLDSENC         VLT_ERROR( VLT_SCP02, 18 )

/*
* Secure Channel SCP03 specific
*/
#define ESCP03DERSESSKEYNULLPARAM VLT_ERROR( VLT_SCP03, 0 )
#define ESCP03INVLDDEVCRYPTO      VLT_ERROR( VLT_SCP03, 1 )
#define ESCP03EXTAUTHFAIL         VLT_ERROR( VLT_SCP03, 2 )
#define ESCP03ADDMACNULLPARAM     VLT_ERROR( VLT_SCP03, 3 )
#define ESCP03CALCMACINVLDMODE    VLT_ERROR( VLT_SCP03, 4 )
#define ESCP03INITNULLPARAM       VLT_ERROR( VLT_SCP03, 5 )
#define ESCP0UNWRAPNULLPARAM      VLT_ERROR( VLT_SCP03, 6 )
#define ESCP03INVLDCMAC           VLT_ERROR( VLT_SCP03, 7 )
#define ESCP03INVLDRMAC           VLT_ERROR( VLT_SCP03, 8 )
#define ESCP03ENCCMDDATANULLPARAM VLT_ERROR( VLT_SCP03, 9 )
#define ESCP03DECCMDDATANULLPARAM VLT_ERROR( VLT_SCP03, 10 )
#define ESCP03WRAPNULLPARAM       VLT_ERROR( VLT_SCP03, 11 )
#define ESCP03GETOVHDNULLPARAM    VLT_ERROR( VLT_SCP03, 12 )
#define ESCP03GETOVHDINVLDMODE    VLT_ERROR( VLT_SCP03, 13 )
#define ESCP03INITINVLDSMAC       VLT_ERROR( VLT_SCP03, 14 )
#define ESCP03INITINVLDSENC       VLT_ERROR( VLT_SCP03, 15 )

/*
* Key Wrapping specific error codes
*/
#define EKWINITNULLPARAM      VLT_ERROR( VLT_KEY_WRAP, 0 )
#define EKWINITINVLDKTSKEY    VLT_ERROR( VLT_KEY_WRAP, 1 )
#define EKWWKNULLPARAM        VLT_ERROR( VLT_KEY_WRAP, 2 )
#define EKWWKSCPENBLD         VLT_ERROR( VLT_KEY_WRAP, 3 )
#define EKWUKNULLPARAM        VLT_ERROR( VLT_KEY_WRAP, 4 )
#define EKWUKSCPENBLD         VLT_ERROR( VLT_KEY_WRAP, 5 )
#define EKWRKINVLDRSP         VLT_ERROR( VLT_KEY_WRAP, 6 )
#define EKWUKSCIVLDCRC        VLT_ERROR( VLT_KEY_WRAP, 7 )
#define EKWUKWNOROOM          VLT_ERROR( VLT_KEY_WRAP, 8 )
#define EKWINITSCPENBLD       VLT_ERROR( VLT_KEY_WRAP, 9 )
#define EKWWKUNINIT           VLT_ERROR( VLT_KEY_WRAP, 10 )
#define EKWUKUNINIT           VLT_ERROR( VLT_KEY_WRAP, 11 )
#define EKWINITINVLDALGOID    VLT_ERROR( VLT_KEY_WRAP, 12 )

/*
 * MS Authentication specific error codes
 */
#define EMSINITNULLPARAM      VLT_ERROR( VLT_MS_AUTH, 0 )
#define EMSINITUPDTFAIL       VLT_ERROR( VLT_MS_AUTH, 1 )
#define EMSUSERNOTMS          VLT_ERROR( VLT_MS_AUTH, 2 )
#define EMSCGRAMNULLPARAM     VLT_ERROR( VLT_MS_AUTH, 3 )
#define EMSINITINVDPARAM      VLT_ERROR( VLT_MS_AUTH, 4 )
#define EMSEXTAUTHFAIL        VLT_ERROR( VLT_MS_AUTH, 5 )

/*
* Identity Authentication specific error codes
*/
#define EIDINITNULLPARAM      VLT_ERROR( VLT_ID_AUTH, 0 )
#define EIDINITSCPNULLPARAM   VLT_ERROR( VLT_ID_AUTH, 1 )
#define EIDSTATENULLPARAM     VLT_ERROR( VLT_ID_AUTH, 2 )
#define EIDNULLBLOBBASE       VLT_ERROR( VLT_ID_AUTH, 10 )
/* ALL VALUES BETWEEN 10 -> 19 are reserved for NULL
 * KEY_BLOB pointer errors, 10 being the first element
 * of the array and 11 being element 1 ....
 */
#define EIDNULLKEYBASE        VLT_ERROR( VLT_ID_AUTH, 20 )
/* ALL VALUES BETWEEN 20 -> 29 are reserved for NULL
 * KEY_BLOB key pointer errors, 20 being the first element
 * of the array and 11 being element 1 ....
 */
#define EIDNUMKEYS            VLT_ERROR( VLT_ID_AUTH, 21 )


/*
 * Identity Authentication version 2 specific error codes
 */
#define EID2INITNULLPARAM     VLT_ERROR( VLT_ID_AUTH2, 1 )
#define EID2NULLBLOBBASE      VLT_ERROR( VLT_ID_AUTH2, 2 )
#define EID2NULLKEYBASE       VLT_ERROR( VLT_ID_AUTH2, 3 )
#define EID2SCPNOSUPPORT      VLT_ERROR( VLT_ID_AUTH2, 4 )
#define EID2MSNOSUPPORT       VLT_ERROR( VLT_ID_AUTH2, 5 )
#define EID2STRONGNOSUPPORT   VLT_ERROR( VLT_ID_AUTH2, 6 )
#define EID2AUTHMETHODNS      VLT_ERROR( VLT_ID_AUTH2, 7 )


/*
* File System specific error codes
*/
#define EFSOPNNULLPARAM       VLT_ERROR( VLT_FILE_SYS, 0 )
#define EFSOPNINVLDTRNMD      VLT_ERROR( VLT_FILE_SYS, 1 )
#define EFSCRTNULLPARAMS      VLT_ERROR( VLT_FILE_SYS, 2 )
#define EFSCRTINVLDENTRYTYP   VLT_ERROR( VLT_FILE_SYS, 3 )
#define FSDLTNULLPARAMS       VLT_ERROR( VLT_FILE_SYS, 4 )
#define EFSDLTFILERECSV       VLT_ERROR( VLT_FILE_SYS, 5 )
#define EFSDLTFOLRECSV        VLT_ERROR( VLT_FILE_SYS, 6 )
#define EFSRDNULLPARAMS       VLT_ERROR( VLT_FILE_SYS, 7 )
#define EFSWRTNULLPARAMS      VLT_ERROR( VLT_FILE_SYS, 8 )
#define EFSWRTINVLDRCLMMD     VLT_ERROR( VLT_FILE_SYS, 9 )
#define EFSSKINVLDORGN        VLT_ERROR( VLT_FILE_SYS, 10 )
#define EFSSKEOFSEEK          VLT_ERROR( VLT_FILE_SYS, 11 )
#define EFSOPNNOTFILE         VLT_ERROR( VLT_FILE_SYS, 12 )
#define EFSOPNALRDYOPN        VLT_ERROR( VLT_FILE_SYS, 13 )
#define EFSRDNOFILEOPN        VLT_ERROR( VLT_FILE_SYS, 14 )
#define EFSWRTNOFILEOPN       VLT_ERROR( VLT_FILE_SYS, 15 )
#define EFSSKNOFILEOPN        VLT_ERROR( VLT_FILE_SYS, 16 )
#define EFSCLSNOFILEOPN       VLT_ERROR( VLT_FILE_SYS, 17 )
#define EFSOPNINVLDNMLEN      VLT_ERROR( VLT_FILE_SYS, 18 )
#define EFSCRTINVLDNMLEN      VLT_ERROR( VLT_FILE_SYS, 19 )
#define EFSDLTINVLDNMLEN      VLT_ERROR( VLT_FILE_SYS, 20 )
#define EFSDLTINVLDENTRYTYP   VLT_ERROR( VLT_FILE_SYS, 21 )
#define EFSOPNSLCTFLD         VLT_ERROR( VLT_FILE_SYS, 22 )
#define EFSSWDINVLDPTH        VLT_ERROR( VLT_FILE_SYS, 23 )
#define EFSSWDINVLDPTHLEN     VLT_ERROR( VLT_FILE_SYS, 24 )
#define EFSSWDENTRYTOOLONG    VLT_ERROR( VLT_FILE_SYS, 25 )
#define EFSSWDNULLPARAMS      VLT_ERROR( VLT_FILE_SYS, 26 )
#define EFSCRTFILEALRDYOPN    VLT_ERROR( VLT_FILE_SYS, 27 )
#define EFSDLTFILEALRDYOPN    VLT_ERROR( VLT_FILE_SYS, 28 )
#define EFSLSTNULLPARAMS      VLT_ERROR( VLT_FILE_SYS, 29 )
#define EFSLSTINVLDRESPLEN    VLT_ERROR( VLT_FILE_SYS, 30 )
#define EFSLSTALRDYOPN        VLT_ERROR( VLT_FILE_SYS, 31 )
#define EFSCFPBYTBTNULLPARAM  VLT_ERROR( VLT_FILE_SYS, 32 )
#define EFSCFPBTBYTNULLPARAM  VLT_ERROR( VLT_FILE_SYS, 33 )
#define EFSCONVPRVACC         VLT_ERROR( VLT_FILE_SYS, 34 )
#define EFSCONVACCPRV         VLT_ERROR( VLT_FILE_SYS, 35 )
#define EFSSTPRIVNULLPARAM    VLT_ERROR( VLT_FILE_SYS, 36 )
#define EFSSTPRIVINVLDLEN     VLT_ERROR( VLT_FILE_SYS, 37 )
#define EFSSTATTRBINVLDLEN    VLT_ERROR( VLT_FILE_SYS, 38 )
#define EFSLSTINVLDLEN        VLT_ERROR( VLT_FILE_SYS, 39 )
#define EFSSTATTRNULLPARAM    VLT_ERROR( VLT_FILE_SYS, 40 )
#define EFSLSTENTRYNOTFLDR    VLT_ERROR( VLT_FILE_SYS, 41 )
#define EFSSETPRIVALRDYOPN    VLT_ERROR( VLT_FILE_SYS, 42 )
#define EFSSETATTRALRDYOPN    VLT_ERROR( VLT_FILE_SYS, 43 )
#define EFSRDSEEKFAILED       VLT_ERROR( VLT_FILE_SYS, 44 )
#define EFSRDINVDLEN          VLT_ERROR( VLT_FILE_SYS, 45 )
#define EFSWRINVDLEN          VLT_ERROR( VLT_FILE_SYS, 46 )
#define EFSWRSEEKFAILED       VLT_ERROR( VLT_FILE_SYS, 47 )

/**
 * CRC16 CCITT Specific Error Codes.
 */
#define ECRC16NULLCRCVAL      VLT_ERROR( VLT_CRC16, 0 )
#define ECRC16NULLBLOCK       VLT_ERROR( VLT_CRC16, 1 )

/**
 * Strong Authentication Specific Error Codes
 */
#define ESTRONGINITNULLPARAM    VLT_ERROR( VLT_STRONG_AUTH, 0 )
#define ESTRONGGENRANDFAIL      VLT_ERROR( VLT_STRONG_AUTH, 1 )
#define ESTRONGINTAUTHFAIL      VLT_ERROR( VLT_STRONG_AUTH, 2 )
#define ESTRONGGENSIGNIDFAIL    VLT_ERROR( VLT_STRONG_AUTH, 3 )
#define ESTRONGGENASSURANCEFAIL VLT_ERROR( VLT_STRONG_AUTH, 4 )
#define ESTRONGVERASSMSGFAIL    VLT_ERROR( VLT_STRONG_AUTH, 5 )
#define ESTRONGAUTHFAIL         VLT_ERROR( VLT_STRONG_AUTH, 6 )
#define EINTERNALAUTHVERFAILED  VLT_ERROR( VLT_STRONG_AUTH, 7 )
#define EASSURANCEMSGSIGNFAILED VLT_ERROR( VLT_STRONG_AUTH, 8 )
#define EEXTERNALAUTHSIGNFAILED VLT_ERROR( VLT_STRONG_AUTH, 9 )
#define EREADPUBLICKEYFAILED    VLT_ERROR( VLT_STRONG_AUTH, 10 )

/**
 * Crypto Service Provider Specific Error Codes
 */
#define ECRYPTOINITNULLPARAM    VLT_ERROR( VLT_CRYPTO, 0 )
#define ECRYPTOCLSNOTSUPPORTED  VLT_ERROR( VLT_CRYPTO, 1 )
#define ECRYPTODFNOTSUPPORTED   VLT_ERROR( VLT_CRYPTO, 2 )
#define ECRYPTOUPDNOTSUPPORTED  VLT_ERROR( VLT_CRYPTO, 3 )
#define ECRYPTOALGNOTSUP        VLT_ERROR( VLT_CRYPTO, 4 )
#define ECRYPTODFNULLPARAM      VLT_ERROR( VLT_CRYPTO, 5 )
#define ECRYPTOUNULLPARAM       VLT_ERROR( VLT_CRYPTO, 6 )


/**
 * ECDSA Signer Service Provider Error Codes
 */
#define EECDSAINITNULLPARAM     VLT_ERROR( VLT_ECDSA, 0 )
#define EECDSAINUPNULLPARAM     VLT_ERROR( VLT_ECDSA, 1 )
#define EECDSAINDFINNULLPARAM   VLT_ERROR( VLT_ECDSA, 2 )
#define EECDSAOPMODENOTSUPP     VLT_ERROR( VLT_ECDSA, 3 )
#define EECDSAINVALIDPARAM      VLT_ERROR( VLT_ECDSA, 4 )
#define EECDSAEXECUTIONERROR    VLT_ERROR( VLT_ECDSA, 5 )

#endif /*VAULTIC_ERR_H*/
